### ISSUE TITLE
Package fails to install on M1 Macbook

### ISSUE THREAD

**Issue by tgarc** [saleae/logic2-automation#29]
I'm unable to install the logic2 pip package on my M1 Macbook, log is shown below. My setup is a fresh conda environment with python3.9. I have seen very similar issues around the web related to installing the grpcio package on an M1 mac, but I have no issues installing grpcio and grpcio-tools on their own.

```
❯ pip install logic2-automation
Looking in indexes: https://pypi.org/simple
Collecting logic2-automation
  Using cached logic2_automation-1.0.6.tar.gz (16 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/opt/homebrew/Caskroom/miniconda/base/envs/test/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/Caskroom/miniconda/base/envs/test/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/homebrew/Caskroom/miniconda/base/envs/test/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/wl/qfb1dl254zs1hzh9fy09tj_h0000gq/T/pip-build-env-v_rqs5y7/overlay/lib/python3.9/site-packages/hatchling/build.py", line 56, in build_wheel
          return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
        File "/private/var/folders/wl/qfb1dl254zs1hzh9fy09tj_h0000gq/T/pip-build-env-v_rqs5y7/overlay/lib/python3.9/site-packages/hatchling/builders/plugin/interface.py", line 150, in build
          build_hook.initialize(version, build_data)
        File "/private/var/folders/wl/qfb1dl254zs1hzh9fy09tj_h0000gq/T/pip-install-0w5kxo1j/logic2-automation_43bb1a8a38844bc8aab39144467b6387/grpc_build_hook.py", line 22, in initialize
          build_protobufs('./proto')
        File "/private/var/folders/wl/qfb1dl254zs1hzh9fy09tj_h0000gq/T/pip-install-0w5kxo1j/logic2-automation_43bb1a8a38844bc8aab39144467b6387/grpc_build_hook.py", line 2, in build_protobufs
          import grpc_tools.protoc
        File "/private/var/folders/wl/qfb1dl254zs1hzh9fy09tj_h0000gq/T/pip-build-env-v_rqs5y7/normal/lib/python3.9/site-packages/grpc_tools/protoc.py", line 20, in <module>
          from grpc_tools import _protoc_compiler
      ImportError: dlopen(/private/var/folders/wl/qfb1dl254zs1hzh9fy09tj_h0000gq/T/pip-build-env-v_rqs5y7/normal/lib/python3.9/site-packages/grpc_tools/_protoc_compiler.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by timreyes** [comment]
Sorry for the trouble with this! I see that you've sent an email to our support team about this issue. I'll go ahead and close this GitHub Issue for now. Let's continue our chat in that email chain.
