### ISSUE TITLE
`pip install logic2-automation` is failing

### ISSUE THREAD

**Issue by huffman** [saleae/logic2-automation#33]
```
pip install logic2-automation
Collecting logic2-automation
  Using cached logic2_automation-1.0.6.tar.gz (16 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Building logic2-automation protobuf files
      Traceback (most recent call last):
        File "C:\Users\huffman\dev\test-logic2-automation\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\huffman\dev\test-logic2-automation\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\huffman\dev\test-logic2-automation\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\huffman\dev\test-logic2-automation\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\huffman\AppData\Local\Temp\pip-build-env-no8xozzi\overlay\Lib\site-packages\hatchling\build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
        File "C:\Users\huffman\AppData\Local\Temp\pip-build-env-no8xozzi\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 155, in build
          artifact = version_api[version](directory, **build_data)
        File "C:\Users\huffman\AppData\Local\Temp\pip-build-env-no8xozzi\overlay\Lib\site-packages\hatchling\builders\wheel.py", line 405, in build_standard
          for included_file in self.recurse_included_files():
        File "C:\Users\huffman\AppData\Local\Temp\pip-build-env-no8xozzi\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 177, in recurse_included_files
          yield from self.recurse_forced_files(self.config.get_force_include())
        File "C:\Users\huffman\AppData\Local\Temp\pip-build-env-no8xozzi\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 231, in recurse_forced_files
          raise FileNotFoundError(msg)
      FileNotFoundError: Forced include not found: C:\Users\huffman\AppData\Local\Temp\pip-install-9b1nuh82\proto\saleae\grpc\saleae.proto
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by gbarkadiusz** [comment]
Related pr. https://github.com/saleae/logic2-automation/pull/34. Confirmed, these temporary changes works.

**Comment by ofek** [comment]
https://github.com/saleae/logic2-automation/pull/34#issuecomment-1852262554
